services:
 app:
    image: docker.io/library/caddy:latest
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - data:/data
      - config:/config
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - default
      - proxy

volumes:
  data:
  config:

networks:
  default:
  proxy:
