services:
  reverse-proxy:
    image: ghcr.io/trly/caddy:main
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - '80:80'
      - '443:443'
    x-podman-env-secrets:
      porkbun-api-key: PORKBUN_API_KEY
      porkbun-api-secret-key: PORKBUN_API_SECRET_KEY
      acme-email: ACME_EMAIL
    networks:
      - default
      - proxy

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_HOST=infrastructure-unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    x-podman-env-secrets:
      unifi-mongo-password: MONGO_PASS
    depends_on:
      - unifi-db
    networks:
      - proxy
      - unifi
    volumes:
      - unifi-config:/config
    restart: unless-stopped

  unifi-db:
    image: docker.io/library/mongo:8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_USER=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    x-podman-env-secrets:
      unifi-mongo-root-password: MONGO_INITDB_ROOT_PASSWORD
      unifi-mongo-password: MONGO_PASS
    networks:
      - unifi
    volumes:
      - unifi-db-data:/data/db
      - ./unifi-init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro,z
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://infrastructure-keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_HOSTNAME=sso.home.trly.dev
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=forwarded
    command: ["start"]
    x-podman-env-secrets:
      kc-db-password: KC_DB_PASSWORD
      kc-admin-user: KC_BOOTSTRAP_ADMIN_USERNAME
      kc-admin-password: KC_BOOTSTRAP_ADMIN_PASSWORD
    depends_on:
      - keycloak-db
    networks:
      - proxy
      - keycloak
    restart: unless-stopped

  keycloak-db:
    image: docker.io/library/postgres:17
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
    x-podman-env-secrets:
      kc-db-password: POSTGRES_PASSWORD
    networks:
      - keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
  unifi-db-data:
  unifi-config:
  keycloak-db-data:

secrets:
  porkbun-api-key:
    external: true
  porkbun-api-secret-key:
    external: true
  acme-email:
    external: true
  unifi-mongo-password:
    external: true
  unifi-mongo-root-password:
    external: true
  kc-admin-user:
    external: true
  kc-admin-password:
    external: true
  kc-db-password:
    external: true
networks:
  default:
  proxy:
  keycloak:
  unifi:
