services:
  reverse-proxy:
    image: ghcr.io/trly/caddy:main
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - '80:80'
      - '443:443'
    x-podman-env-secrets:
      porkbun-api-key: PORKBUN_API_KEY
      porkbun-api-secret-key: PORKBUN_API_SECRET_KEY
      acme-email: ACME_EMAIL
    networks:
      - default
      - proxy

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    x-podman-env-secrets:
      unifi-mongo-password: MONGO_PASS
    volumes:
      - unifi-config:/config
    restart: unless-stopped

  unifi-db:
    image: docker.io/library/mongo:8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_USER=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    x-podman-env-secrets:
      unifi-mongo-root-password: MONGO_INITDB_ROOT_PASSWORD
      unifi-mongo-password: MONGO_PASS
    volumes:
      - unifi-db-data:/data/db
      - ./unifi-init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
  unifi-db-data:
  unifi-config:

secrets:
  porkbun-api-key:
    external: true
  porkbun-api-secret-key:
    external: true
  acme-email:
    external: true
  unifi-mongo-password:
    external: true
  unifi-mongo-root-password:
    external: true

networks:
  default:
  proxy:
  unifi:

