services:
  reverse-proxy:
    image: ghcr.io/trly/caddy:main
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - '80:80'
      - '443:443'
    x-podman-env-secrets:
      porkbun-api-key: PORKBUN_API_KEY
      porkbun-api-secret-key: PORKBUN_API_SECRET_KEY
      acme-email: ACME_EMAIL
    networks:
      - default
      - proxy

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_HOST=infrastructure-unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    x-podman-env-secrets:
      unifi-mongo-password: MONGO_PASS
    depends_on:
      - unifi-db
    networks:
      - proxy
      - unifi
    volumes:
      - unifi-config:/config
    restart: unless-stopped

  unifi-db:
    image: docker.io/library/mongo:8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_USER=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    x-podman-env-secrets:
      unifi-mongo-root-password: MONGO_INITDB_ROOT_PASSWORD
      unifi-mongo-password: MONGO_PASS
    networks:
      - unifi
    volumes:
      - unifi-db-data:/data/db
      - ./unifi-init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro,z
    restart: unless-stopped

  authelia:
    image: ghcr.io/authelia/authelia:4.39.4
    restart: unless-stopped
    environment:
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia-jwt-secret
      - AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia-session-secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia-storage-encryption-key
    secrets:
      - authelia-jwt-secret
      - authelia-session-secret
      - authelia-storage-encryption-key
    volumes:
      - authelia-data:/config
      - ./authelia/configuration.yml:/config/configuration.yml:ro,z
    networks:
      - authelia
      - proxy

volumes:
  caddy-data:
  caddy-config:
  unifi-db-data:
  unifi-config:
  authelia-data:

secrets:
  porkbun-api-key:
    external: true
  porkbun-api-secret-key:
    external: true
  acme-email:
    external: true
  unifi-mongo-password:
    external: true
  unifi-mongo-root-password:
    external: true
  authelia-session-secret:
    external: true
  authelia-storage-encryption-key:
    external: true
  authelia-jwt-secret:
    external: true

networks:
  default:
  proxy:
  unifi:
  authelia:
