services:
  influxdb:
    image: docker.io/library/influxdb:2.2
    restart: always
    volumes:
      - 'scrutiny-influxdb:/var/lib/influxdb2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - default

  web:
    container_name: scrutiny-web
    image: 'ghcr.io/analogj/scrutiny:master-web'
    restart: always
    volumes:
      - 'scrutiny-config:/opt/scrutiny/config'
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'scrutiny-influxdb'
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    networks:
      - default
      - infrastructure-proxy

  collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    restart: always
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - '/run/udev:/run/udev:ro'
    environment:
      COLLECTOR_API_ENDPOINT: 'http://scrutiny-web:8080'
      COLLECTOR_HOST_ID: 'polaris'
      COLLECTOR_RUN_STARTUP: true
    depends_on:
      - web
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    networks:
      - default

volumes:
  scrutiny-influxdb:
    name: scrutiny-scrutiny-influxdb
    external: true
  scrutiny-config:
    name: scrutiny-scrutiny-config
    external: true

networks:
  default:
  infrastructure-proxy:
    external: true
