services:
  app:
    image: docker.gitea.com/gitea:1.25
    restart: always
    volumes:
      - data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - infrastructure-proxy

volumes:
  data:

networks:
  default:
  infrastructure-proxy:
    external: true
