FROM cgr.dev/chainguard/python:latest-dev

WORKDIR /app
RUN pip install mcpo uv
EXPOSE 8000
CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "uvx", "mcp-server-time", "--local-timezone=America/Detroit"]
