services:
  app:
    image: docker.io/traefik/whoami:latest
    restart: always
    environment:
      WHOAMI_PORT_NUMBER: 8081
    networks:
      - default
      - caddy-app
    ports:
      - "127.0.0.1:8081:8081"

networks:
  caddy-proxy:
    external: true
