services:
  web:
    container_name: miniflux-web
    image: docker.io/miniflux/miniflux:latest
    depends_on:
      db:
        condition: service_started
    environment:
      - RUN_MIGRATIONS=1
      - OAUTH2_PROVIDER=oidc
      - OAUTH2_REDIRECT_URL=https://rss.home.trly.dev/oauth2/oidc/callback
    x-podman-env-secrets:
      miniflux-db-url: DATABASE_URL
      pocket-id-discovery-endpoint: OAUTH2_OIDC_DISCOVERY_ENDPOINT
      miniflux-oauth2-client-id: OAUTH2_CLIENT_ID
      miniflux-oauth2-client-secret: OAUTH2_CLIENT_SECRET
    networks:
      - default
      - infrastructure-proxy
  db:
    image: docker.io/library/postgres:17-alpine
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_DB=miniflux
    x-podman-env-secrets:
      miniflux-db-password: POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - default

volumes:
  db-data:
    name: miniflux_db-data

networks:
  default:
  infrastructure-proxy:
    external: true

secrets:
  pocket-id-discovery-endpoint:
    external: true
  miniflux-oauth2-client-id:
    external: true
  miniflux-oauth2-client-secret:
    external: true
  miniflux-db-password:
    external: true
  miniflux-db-url:
    external: true

