services:
  gitea:
    image: docker.gitea.com/gitea:1.25
    restart: always
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - infrastructure-proxy

volumes:
  gitea-data:

networks:
  default:
  infrastructure-proxy:
    external: true
