services:
  app:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-app
    restart: always
    environment:
      - OPENAI_API_BASE_URLS=https://openrouter.ai/api/v1
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_OLLAMA_API=true
      - ENABLE_BASE_MODELS_CACHE=True
      - MODELS_CACHE_TTL=300
      - ENABLE_QUERIES_CACHE=True
      - RAG_SYSTEM_CONTEXT=True
      - ENABLE_REALTIME_CHAT_SAVE=False
      - ENABLE_AUTOCOMPLETE_GENERATION=False
      - CHAT_RESPONSE_STREAM_DELTA_CHUNK_SIZE=5
    x-quad-ops-env-secrets:
      openrouter-api-key: OPENAI_API_KEYS
    volumes:
      - data:/app/backend/data
    networks:
      - default
      - infrastructure-proxy

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: open-webui-ollama
    hostname: ollama
    restart: always
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama:/root/.ollama:z
    networks:
      - default
      - infrastructure-proxy

volumes:
  data:
  ollama:

networks:
  default:
  infrastructure-proxy:
    external: true

secrets:
  openrouter-api-key:
    external: true
