services:
  app:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-app
    restart: always
    environment:
      - OPENAI_API_BASE_URLS=http://llama:8080/v1
      - ENABLE_BASE_MODELS_CACHE=True
      - MODELS_CACHE_TTL=300
      - ENABLE_QUERIES_CACHE=True
      - RAG_SYSTEM_CONTEXT=True
      - ENABLE_REALTIME_CHAT_SAVE=False
      - ENABLE_AUTOCOMPLETE_GENERATION=False
      - CHAT_RESPONSE_STREAM_DELTA_CHUNK_SIZE=5
    x-quad-ops-env-secrets:
      openrouter-api-key: OPENAI_API_KEYS
    volumes:
      - data:/app/backend/data
    networks:
      - default
      - infrastructure-proxy

  llm:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: open-webui-llm
    hostname: llama
    restart: always
    environment:
      - LD_LIBRARY_PATH=/app
    working_dir: /models
    command: >
      --hf-repo bartowski/Llama-3.2-3B-Instruct-GGUF
      --hf-file Llama-3.2-3B-Instruct-Q4_K_M.gguf
      --host 0.0.0.0
      --port 8080
      -c 4096
    volumes:
      - models:/models:z
    networks:
      - default
      - infrastructure-proxy

volumes:
  data:
  models:
    name: ai_models

networks:
  default:
  infrastructure-proxy:
    external: true

secrets:
  openrouter-api-key:
    external: true
