services:
  cadvisor:
    image: ghcr.io/google/cadvisor:v0.53.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/containers:/var/lib/containers:ro'
      - '/dev/disk:/dev/disk:ro'
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - default
    ports:
      - "8080:8080"
