services:
  cadvisor:
    image: ghcr.io/google/cadvisor:v0.53.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/containers:/var/lib/containers:ro'
      - '/dev/disk:/dev/disk:ro'
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - default
      - infrastructure-proxy
    ports:
      - "8080:8080"
  server:
    image: docker.io/prom/prometheus:v3.4.2
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro,z
    networks:
      - default
      - infrastructure-proxy

  perses:
    image: docker.io/persesdev/perses:v0.51.0
    networks:
      - default
      - infrastructure-proxy
    volumes:
      - perses-data:/perses

networks:
  default:
  infrastructure-proxy:
    external: true

volumes:
  prometheus-data:
  perses-data:
