global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: immich_api
  static_configs:
    - targets: ['media-immich-server:8081']

- job_name: immich_microservices
  static_configs:
    - targets: ['media-immich-server:8082']
