services:
  reverse-proxy:
    image: ghcr.io/trly/caddy:main
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
      - proxy

secrets:
  porkbun-api-key:
    external: true
  porkbun-api-secret-key:
    external: true
  acme-email:
    external: true

volumes:
  caddy-data:
  caddy-config:

networks:
  default:
  proxy:
