services:
  pki:
    image: docker.io/smallstep/step-ca:latest
    restart: always
    volumes:
    - certificate-authority:/home/step
    networks:
    - default

    environment:
      DOCKER_STEPCA_INIT_NAME: "Taylor Family CA"
      DOCKER_STEPCA_INIT_DNS_NAMES: "*.media.localdomain,media.localdomain"
      DOCKER_STEPCA_INIT_ADDRESS: ":9000"
      DOCKER_STEPCA_INIT_PROVISIONER_NAME: "acme-media-localdomain"
      DOCKER_STEPCA_INIT_ACME: "true"
      STEPCA_LOG_LEVEL: "info"

    x-podman-env-secrets:
      step-ca-password: DOCKER_STEPCA_INIT_PASSWORD

  reverse-proxy:
    image: ghcr.io/trly/caddy:main
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
      - proxy

    x-quad-ops-init:
      - image: cgr.dev/chainguard/curl:latest
        command: ["-k", "-XGET", "https://infrastructure-pki:9000/roots.pem", "-o", "/config/step_ca.crt"]

secrets:
  step-ca-password:
    external: true

volumes:
  caddy-data:
  caddy-config:
  certificate-authority:

networks:
  default:
  proxy:
