services:
  hub:
    image: docker.io/henrygd/beszel:latest
    restart: unless-stopped
    networks:
      - default
      - infrastructure-proxy
    volumes:
      - beszel-data:/beszel_data
      - beszel-socket:/beszel_socket

  agent:
    image: docker.io/henrygd/beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
      - beszel-socket:/beszel_socket
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: beszel-socket/beszel.sock
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB0nf/qweHVef91/u/8MvRcu99ZzCZiTuCx88xzmVwmF"

volumes:
  beszel-data:
  beszel-socket:

networks:
  default:
  infrastructure-proxy:
    external: true
